// Mapa de nome do país (em inglês, como vem do TheSportsDB) -> código ISO 2 letras
export const COUNTRY_CODES: Record<string, string> = {
  Argentina: "AR",
  Australia: "AU",
  Austria: "AT",
  Belgium: "BE",
  Brazil: "BR",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  Colombia: "CO",
  "Costa Rica": "CR",
  Croatia: "HR",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  Denmark: "DK",
  Ecuador: "EC",
  Egypt: "EG",
  England: "GB-ENG",
  France: "FR",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Iran: "IR",
  Italy: "IT",
  "Ivory Coast": "CI",
  Japan: "JP",
  "South Korea": "KR",
  Korea: "KR",
  "Republic of Korea": "KR",
  Mexico: "MX",
  Morocco: "MA",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  Norway: "NO",
  Panama: "PA",
  Paraguay: "PY",
  Peru: "PE",
  Poland: "PL",
  Portugal: "PT",
  Qatar: "QA",
  "Saudi Arabia": "SA",
  Scotland: "GB-SCT",
  Senegal: "SN",
  Serbia: "RS",
  Slovakia: "SK",
  "South Africa": "ZA",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Tunisia: "TN",
  Turkey: "TR",
  "United States": "US",
  USA: "US",
  Uruguay: "UY",
  Wales: "GB-WLS",
  Algeria: "DZ",
  "DR Congo": "CD",
  Mali: "ML",
  "Burkina Faso": "BF",
  "Cape Verde": "CV",
  Jordan: "JO",
  Uzbekistan: "UZ",
  "United Arab Emirates": "AE",
  Iraq: "IQ",
  "New Caledonia": "NC",
  Curacao: "CW",
  Haiti: "HT",
  Jamaica: "JM",
  Bolivia: "BO",
  Venezuela: "VE",
};

export function codigoPais(nome: string | null | undefined): string | null {
  if (!nome) return null;
  return COUNTRY_CODES[nome] ?? null;
}
